### ISSUE TITLE
Cannot update entity on many side of 1:m relationship where key is composite

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#171] opened 2015-02-01 07:43 UTC
Sorry if I'm doing something dumb here, but the following fails (exception details below). This is a major blocker for me.

```C#
[Entity]
public interface ISupplier
{
    string Id
    {
        get;
    }

    ICollection<IProduct> Products
    {
        get;
        set;
    }
}

[Entity]
public interface IProduct
{
    [Identifier(KeyProperties = new[] { "Supplier", "Code" })]
    string Id
    {
        get;
    }

    string Code
    {
        get;
        set;
    }

    string Name
    {
        get;
        set;
    }

    [InverseProperty("Products")]
    ISupplier Supplier
    {
        get;
        set;
    }
}

class Program
{
    static void Main(string[] args)
    {
        var connectionString = "type=embedded;storesdirectory=Stores;storename=Repro";
        var client = BrightstarService.GetClient(connectionString);

        if (client.DoesStoreExist("Repro"))
        {
            client.DeleteStore("Repro");
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var supplier = new Supplier
            {
                Id = "acme"
            };
            var product = new Product
            {
                Code = "abc",
                Name = "Widget",
                Supplier = supplier
            };

            context.Products.Add(product);
            context.SaveChanges();
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var supplier = context
                .Suppliers
                .Where(x => x.Id == "acme")
                .First();
            var product = new Product
            {
                Code = "abc",
                Name = "Widget Renamed",
                Supplier = supplier
            };

            product.Context = context;
            //var trackedObjects = context.TrackedObjects.ToList();

            // FAILS HERE WITH EXCEPTION BELOW
            context.SaveChanges();
        }

        Console.WriteLine("DONE");
        Console.ReadKey();
    }
}
```
Exception details:
```
BrightstarDB.EntityFramework.UniqueConstraintViolationException was unhandled
Message: An unhandled exception of type 'BrightstarDB.EntityFramework.UniqueConstraintViolationException' occurred in BrightstarDB.dll
Additional information: One or more new resources have an identifier that conflicts with an existing resource of the same type.
```

**Comment by kal** [comment] 2015-02-01 13:20
Hi,

I think the cause is the same as for issue #170. When you want to update an entity, rather than creating a new local object, retrieve the entity from the context using a LINQ query and then modify that - the code you have at the moment is trying to create another entity with the same composite ID as an existing entity, hence the exception. For your update code you need something like:

```c#
using (var context = new MyEntityContext(connectionString))
        {
            var supplier = context
                .Suppliers
                .Where(x => x.Id == "acme")
                .First();
            var product = context.Products.FirstOrDefault( x=> x.Code="abc" && x.Supplier=supplier );
            product.Name = "Widget Renamed";
            context.SaveChanges();
        }
```
If nothing else you are saving a few lines of typing !

I'll close this issue for now, but if you are still having problems, just let me know by reopening it.

Cheers

Kal

**Closed by kal** 2015-02-01 13:20 UTC

**Comment by kentcb** [comment] 2015-02-02 00:15
Thanks Kal. My reasoning for creating a new product versus looking up the existing one is as per #170. However, this at least gives me a way forward - it just means I have to manually copy the properties on the product from the external code into the product retrieved from the context.
