### ISSUE TITLE
FileNotFound Exception BrightstarDB.Portable.Desktop

### ISSUE THREAD

**Issue by ebceu4** [BrightstarDB/BrightstarDB#161] opened 2015-01-20 15:55 UTC
Windows Phone 8.0 application 

var dataObjectContext = BrightstarService.GetDataObjectContext("type=embedded;storesdirectory=.;storename=store"); 
throws an exception: FileNotFound BrightstarDB.Portable.Desktop

**Comment by kal** [comment] 2015-01-20 17:39
Which nuget packages have you installed ? You need to install BrightstarDB and BrightstarDB.Platform.
It sounds like the portable platform libraries aren't installed and the probe for a usable platform-specific library is failing (it should actually find and load BrightstarDB.Portable.WindowsPhone which is the assembly that gets installed by the NuGet package I mentioned).

If that isn't the problem, can you share a bit more detail - there are so many different windows phone application project types that it is difficult to know which one to use to reproduce your problem.

**Comment by ebceu4** [comment] 2015-01-22 00:58
I have just opened my project at home to reproduce the problem and it has gone. But then, i opened it again on my office pc where it was originally found and it is still there. I have vs2013 at home and vs2012 at work, so my thought that this issue is somehow associated with SDK versions or with GAC registered libraries.
I opened the same code under different environments and it behaves differently. Under 2012 it reproduces both on emulator and real device.

**Comment by kal** [comment] 2015-01-24 18:50
i just tried this out on a machine with VS2012 (Ultimate Edition) installed. Created a Windows Phone App (targeting Windows Phone OS 8.0); added BrightstarDB and BrightstarDB.Platform nuget packages to the project, then added the following code to the MainPage.xaml.cs (in the constructor after InitializeComponent() is called:

var context = BrightstarDB.Client.BrightstarService.GetDataObjectContext("type=embedded;storesDirectory=.");
if(!context.DoesStoreExist("test")) {
  context.CreateStore("test");
}

I stepped through this code in the debugger and it works fine - no error, or exception thrown.

I also checked that the code works to create and save a data object so as far as I can tell this is working fine. I'm not sure why there is a difference for you although perhaps it is because the machine I'm testing on also has VS2013 installed. 

If you get chance to have a dig into this a bit more on your machine with only VS2012 installed then I would appreciate any further information you can provide.

Cheers

Kal

**Comment by kal** [comment] 2015-04-07 11:07
Any further info on this ? Does the issue still persist with the recent 1.10 release ?

**Comment by kal** [comment] 2015-04-21 18:03
I'm closing this for now - if you still find you have this problem, please add a comment here and we can reopen the issue.

**Closed by kal** 2015-04-21 18:03 UTC
Labels: triage required
