### ISSUE TITLE
UTC DateTimes are converted to Local

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#168] opened 2015-02-01 01:38 UTC
I'm not sure if this is intentional or not, but it certainly seems like it shouldn't be happening to me. If an entity has a `DateTime` (or `DateTime?`) property, any UTC `DateTime` assigned to that property is converted to local time when it is read back.

```C#
[Entity]
public interface ITestEntity
{
    string Id
    {
        get;
    }

    DateTime DateTimeProperty
    {
        get;
        set;
    }

    DateTime? NullableDateTimeProperty
    {
        get;
        set;
    }
}

class Program
{
    static void Main(string[] args)
    {
        var connectionString = "type=embedded;storesdirectory=Stores;storename=Repro";
        var client = BrightstarService.GetClient(connectionString);

        if (client.DoesStoreExist("Repro"))
        {
            client.DeleteStore("Repro");
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var dt = new DateTime(2015, 02, 18, 0, 0, 0, DateTimeKind.Utc);

            var entity = new TestEntity
            {
                DateTimeProperty = dt,
                NullableDateTimeProperty = dt
            };

            context.TestEntities.Add(entity);
            context.SaveChanges();
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var entity = context.TestEntities.Single();

            Console.WriteLine("DateTimeProperty: {0}", entity.DateTimeProperty.Kind);
            Console.WriteLine("NullableDateTimeProperty: {0}", entity.NullableDateTimeProperty.Value.Kind);
        }

        Console.ReadKey();
    }
}
```

The output is:

```
DateTimeProperty: Local
NullableDateTimeProperty: Local
```

**Comment by kal** [comment] 2015-02-01 13:10
This sounds like another effect of the problem reported on issue #165. I'll hopefully have a fix for that committed to the develop branch today or tomorrow. I'll leave this issue open for now until I can verify that the two problems have the same root cause though.

**Comment by kal** [comment] 2015-02-01 16:13
Should now be fixed in the develop branch.

**Closed by kal** 2015-02-01 16:13 UTC
Labels: bug

**Comment by kentcb** [comment] 2015-02-02 00:16
Thanks.
