### ISSUE TITLE
Getting intermittent System.OutOfMemoryExceptions when initialising context in [TestInitialize] method in Unit test

### ISSUE THREAD

**Issue by osawyerr** [BrightstarDB/BrightstarDB#155] opened 2014-12-17 13:15 UTC
I have a machine with 7.5 GB ram physical ram and before the test, the used memory is about 3.5 GB before I run the test, so this should definitely not happen.

This is using an Embedded store with v1.8.0

context = new CacheEntityContext("Type=embedded;StoresDirectory=" + path + ";StoreName=HashStoreTest");
            

Initialization method Desktop.Tests.Cache.HashStoreTest.SetUp threw exception. BrightstarDB.Client.BrightstarClientException: BrightstarDB.Client.BrightstarClientException: Error creating store HashStoreTest. Exception of type 'System.OutOfMemoryException' was thrown. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown..
    at System.Collections.Generic.Dictionary`2.Initialize(Int32 capacity)   at System.Collections.Generic.Dictionary`2..ctor(Int32 capacity, IEqualityComparer`1 comparer)   at BrightstarDB.Utils.LruCache`2..ctor(Int32 limit, Int32 highWatermark, Int32 lowWatermark)   at BrightstarDB.Storage.BPlusTreeStore.ResourceIndex.LruResourceCache..ctor(Int32 limit, Int32 highWatermark, Int32 lowWatermark)   at BrightstarDB.Storage.BPlusTreeStore.ResourceIndex.LruResourceCache..ctor()   at BrightstarDB.Storage.BPlusTreeStore.ResourceIndex.ResourceIndex..ctor(IPageStore pageStore, IResourceTable resourceTable, UInt64 rootNodeId)   at BrightstarDB.Storage.BPlusTreeStore.Store.Load(IPage storePage, BrightstarProfiler profiler)   at BrightstarDB.Storage.BPlusTreeStore.Store..ctor(String storeLocation, IPageStore dataPageStore, IResourceTable resourceTable, UInt64 storePageId, BrightstarProfiler profiler)   at BrightstarDB.Storage.BPlusTreeStore.BPlusTreeStoreManager.OpenStore(String storeLocation, Boolean readOnly)   at BrightstarDB.Storage.BPlusTreeStore.BPlusTreeStoreManager.CreateStore(String storeLocation, PersistenceType storePersistenceType, Boolean readOnly)   at BrightstarDB.Server.ServerCore.CreateStore(String storeName, PersistenceType persistenceType)   at BrightstarDB.Client.EmbeddedBrightstarService.CreateStore(String storeName, PersistenceType persistenceType) --- End of inner exception stack trace ---    at BrightstarDB.Client.EmbeddedBrightstarService.CreateStore(String storeName, PersistenceType persistenceType)   at BrightstarDB.Client.EmbeddedBrightstarService.CreateStore(String storeName)   at BrightstarDB.EntityFramework.BrightstarEntityContext.AssertStoreFromConnectionString(ConnectionString connectionString)   at BrightstarDB.EntityFramework.BrightstarEntityContext..ctor(String connectionString, Nullable`1 enableOptimisticLocking, String updateGraphUri, IEnumerable`1 datasetGraphUris, String versionGraphUri)   at Desktop.Model.CacheEntityContext..ctor(String connectionString, Nullable`1 enableOptimisticLocking, String updateGraphUri, IEnumerable`1 datasetGraphUris, String versionGraphUri) in CacheEntityContext.cs: line 52   at Desktop.Tests.Cache.HashStoreTest.SetUp() in HashStoreTest.cs: line 23

**Comment by kal** [comment] 2015-06-30 13:22
I'm still not able to reproduce this using a command line app that generates byte arrays between 128K and 256K in size (using BrightstarDB 1.10). It runs in batches of 10, using random integers between 1 and 255 as the key. I'm going to close this one for now as "Cannot Reproduce". 

If you are still having the problem let me know and I can take another look, but I'm going to need a bit more help in generating a proper reproduction of the error.

**Closed by kal** 2015-06-30 13:22 UTC
Labels: bug, triage required
