### ISSUE TITLE
Behavior of identifier property seems inconsistent and temperamental

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#183] opened 2015-02-04 09:57 UTC
Running on Windows, the following code throws a `NullReferenceException`:
```C#
[Entity]
public interface IEntity
{
    string Id
    {
        get;
    }
}

var entity = new Entity();

// this line throws
var id = entity.Id;
```
Exception stack (shortened for clarity):
```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=BrightstarDB
  StackTrace:
       at BrightstarDB.EntityFramework.BrightstarEntityObject.GetIdentityBase()
       at BrightstarDB.EntityFramework.BrightstarEntityObject.GetKey()
       at BrightstarDB_REPRO.Entity.get_Id()
```
Similar code on iOS has different behavior: it returns `null` as the value of an unset identifier, but setting it to `null` will subsequently return `string.Empty` as the identifier's value.

This can result in a lot of confusion because seemingly innocent code like this:
```C#
public static ISomeEntity ToEntity(this ISomeContract @this)
{
    return new SomeEntity
    {
        Id = @this.Id,
        Foo = @this.Foo
    };
}
```
can result in an entity with `string.Empty` as its identifier rather than `null` per the contract.

I don't know enough about the internal workings of B* to offer anything other than an outsider's perspective and expectations on how this could work:

* one can always get/set the identifier property without *ever* getting an exception
* getting an unset identifier returns `null`
* setting an identifier to `null` effectively unsets it. Subsequent retrievals of the identifier would therefore return `null`

**Comment by kal** [comment] 2015-02-04 18:56
I'll have to look into this a bit more. I can see where you are coming from but for B* the implementation is a bit different from an ORM because the identity of the resource is fundamental. When I added in the composite key support I updated the code to allow an identity to be changed (previously it was immutable) - and I suspect that those changes are responsible for some of the confusion.

It's always good to get another perspective on things as everyone comes to an API with different expectations and I want to try and strive to make sure that B* conforms to the principal of least suprise (at least for most of the people, most of the time!)

Thanks for taking the time to provide this feedback (and all the others) it really is extremely helpful!

**Comment by kentcb** [comment] 2015-02-05 06:52
You're welcome. Thanks for such a great product!

**Comment by kal** [comment] 2015-02-09 09:30
Hi,

Can you check that this is not a duplicate of #191. The code you provide for Windows looks the same as the code on that bug, so if the problem was related to not having an entity context, that has been fixed. If there is still some other residual problem, just let me know.

Cheers

Kal

**Comment by kentcb** [comment] 2015-02-10 06:19
Hey,

It could be the same underlying problem, but they're different use cases. In this issue I'm getting the ID whereas in #191 I'm attempting to set it.

Cheers

**Comment by kal** [comment] 2015-02-14 15:26
I think that the notion of unsetting an Id is going to be difficult to support. The URI identifier of the entity is the "hook" on which all of the properties are hung. Unlike a relational table where the row could  still exist if the Id column was set to null, a triple store has no rows, the URI is both primary key and "row" in effect.
However I agree that there should be consistency in the value returned by an unset ID in the case where you are testing a new locally created entity before you add it to a context. And getting the value of an unset ID should return null and not throw an exception.

**Comment by kal** [comment] 2015-02-14 15:33
I just added a repro (see the link above).
The NRE is happening because the static initialization of the context is not performed if you don't create a context object. If you either create a context object first or call the static InitializeEntityMappingStore method on the context class, then you will avoid the NRE.

With that caveat, retrieving an unset id does return null on Windows.

**Closed by kal** 2015-02-14 15:33 UTC
Labels: enhancement

**Comment by kentcb** [comment] 2015-02-17 09:05
Hi,

This issue is closed but I still see the problem where setting an entity's ID to `null` results in it becoming an empty string. See the part of my initial message that starts with:

> Similar code on iOS

Should I open a separate issue specifically about this?

**Comment by kal** [comment] 2015-02-17 09:24
In a way the code is behaving "as expected" - by not providing an ID you are generating an RDF resource with a URI consisting only of the prefix, then when you ask for the ID again later the code is splitting of the prefix and returning what is left of the URI - which is an empty string.

In practice this sort of thing is dangerous. If you have a prefix it is because you expect multiple distinct IDs to be generated using that prefix. I think it would be better if setting an ID to null or an empty string is disallowed with an ArgumentException being raised. I'll open a separate issue for this.

**Comment by kentcb** [comment] 2015-02-17 10:35
That would definitely be more helpful than the current behavior. Thanks.
